apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s  # How often to scrape metrics

    scrape_configs:
      - job_name: "backend-metrics"
        metrics_path: "/metrics"
        static_configs:
          - targets: ["backend-service.default.svc.cluster.local:80"]
